import Config

# Configure your database
config :golfex, Golfex.Repo,
  database: Path.expand("../golfex_dev.db", __DIR__),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

config :golfex, GolfexWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "o9b+DYzEw3CUVni8QWdjGZPf0Dlhc+4OphrjqK7wj/PCcJuSPU+FtxvrX4tIMhQv",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:golfex, ~w(--sourcemap=inline --watch)]},
    esbuild_css: {Esbuild, :install_and_run, [:golfex_css, ~w(--watch)]},
    npx:
      ~w(sugarcube generate --watch --silent --force) ++
        [cd: Path.expand("../assets", __DIR__)]
  ]

# Reload browser tabs when matching files change.
config :golfex, GolfexWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      # ## SSL Support
      #
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      #
      #     mix phx.gen.cert
      #
      ~r"lib/golfex_web/router\.ex$"E,
      ~r"lib/golfex_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
config :golfex, dev_routes: true

# Do not include metadata nor timestamps in development logs
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# If desired, both `http:` and `https:` keys can be
# in production as building large stacktraces may be expensive.
# configured to run both http and https servers on
# different ports.
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
